# -*- coding: utf-8 -*-
"""AI DASHBOARD WEEK-2 ASSIGNMENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zqkSJ3_1q2g4tFg8fUewxNW5QBav2nX0
"""

!pip install plotly pandas -q

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

#load the data
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
print("Data Loaded | shape:",df.shape)
df

# ── DATA CLEANING ────────────────────────────────────────────
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df.drop(columns=['Cabin', 'Ticket', 'Name'], inplace=True)
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
print("✅ Data Cleaned | Shape:", df.shape)
print(df.head())

# ── KPIs ─────────────────────────────────────────────────────
total     = len(df)
survived  = df['Survived'].sum()
rate      = round(df['Survived'].mean() * 100, 1)
avg_age   = round(df['Age'].mean(), 1)
avg_fare  = round(df['Fare'].mean(), 2)

print("\n========== KPI SUMMARY ==========")
print(f"  Total Passengers : {total}")
print(f"  Survived         : {survived}")
print(f"  Survival Rate    : {rate}%")
print(f"  Average Age      : {avg_age} yrs")
print(f"  Average Fare     : ${avg_fare}")
print("==================================")

# ── VISUALIZATION 1 : Survival Count ─────────────────────────
fig1 = px.bar(
    df['Survived'].value_counts().reset_index(),
    x='Survived', y='count',
    color='Survived',
    title='Survival Count (0 = Died, 1 = Survived)',
    color_discrete_sequence=['#EF553B', '#00CC96'],
    labels={'count': 'Number of Passengers'}
)
fig1.update_xaxes(tickvals=[0, 1], ticktext=['Died', 'Survived'])
fig1.show()

# ── VISUALIZATION 2 : Survival by Passenger Class ────────────
fig2 = px.histogram(
    df, x='Pclass', color='Survived',
    barmode='group',
    title='Survival by Passenger Class',
    labels={'Pclass': 'Class', 'count': 'Passengers'},
    color_discrete_sequence=['#EF553B', '#00CC96']
)
fig2.show()

# ── VISUALIZATION 3 : Age Distribution ───────────────────────
fig3 = px.histogram(
    df, x='Age', nbins=30,
    color='Survived',
    title='Age Distribution by Survival',
    labels={'Age': 'Passenger Age'},
    color_discrete_sequence=['#EF553B', '#00CC96']
)
fig3.show()

# ── VISUALIZATION 4 : Fare Distribution by Class ─────────────
fig4 = px.box(
    df, x='Pclass', y='Fare',
    color='Pclass',
    title='Fare Distribution by Passenger Class',
    labels={'Pclass': 'Class'}
)
fig4.show()

# ── VISUALIZATION 5 : Gender Survival Pie Chart ──────────────
surv_gender = df[df['Survived'] == 1]['Sex'].value_counts()
fig5 = px.pie(
    values=surv_gender.values,
    names=surv_gender.index,
    title='Survivors by Gender',
    color_discrete_sequence=['#636EFA', '#EF553B']
)
fig5.show()

# ── INTERACTIVE FILTER ───────────────────────────────────────
print("\n── Filter: Female Passengers in Class 1 ──")
filtered = df[(df['Sex'] == 'female') & (df['Pclass'] == 1)]
print(filtered[['Age', 'Fare', 'Survived', 'FamilySize']].describe().round(2))